apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            branch: dev
            namespace: dev
          - name: stage
            branch: stage
            namespace: stage
          - name: prod
            branch: main
            namespace: prod
  template:
    metadata:
      name: guestbook-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/Cyto989/argocd-app-config.git
        targetRevision: '{{branch}}'
        path: '.'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true