apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            branch: dev
            namespace: dev
          - name: stage
            branch: stage
            namespace: stage
<<<<<<< HEAD
          - name: prod
            branch: main
            namespace: prod
=======
          - name: main
            branch: main
            namespace: main
>>>>>>> bd91ef1802abf47a9e384d9e75ae282a087cfa85
  template:
    metadata:
      name: guestbook-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/Cyto989/argocd-app-config.git
        targetRevision: '{{branch}}'
<<<<<<< HEAD
        path: 'app'  # Use 'app' directory for all branches
=======
        path: '{{name}}'
>>>>>>> bd91ef1802abf47a9e384d9e75ae282a087cfa85
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
<<<<<<< HEAD
          - CreateNamespace=true
=======
        - CreateNamespace=true
>>>>>>> bd91ef1802abf47a9e384d9e75ae282a087cfa85
